config/routes.rb
Centralestudantil::Application.routes.draw do
  devise_for :users
  resources :institutions
  resources :courses
  resources :periods
  root to: 'pages#home'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :name
  belongs_to :period
  validates :name, presence: true, uniqueness: true, length: { maximum: 1 }
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :name, :institution
  has_many :periods
  has_many :subjects
  belongs_to :institution
  validates :name, :institution, presence: true
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  attr_accessible :name
  has_many :courses
  validates :name, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :number, :kind
  belongs_to :course
  has_many :classrooms
  validates :number, presence: true
  validates :kind, presence: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name
  belongs_to :course
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
    @course = Course.new
  end

  def create
    @course = Course.new(params[:course])
    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @course = Course.find(params[:id])
  end

  def destroy
    course = Course.find(params[:id])
    course.destroy!
    redirect_to courses_path
  end

  def update
    @course = Course.find(params[:id])
    @course.update!(params[:course])
    redirect_to @course
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  def index
    @institutions = Institution.all
  end

  def new
    @institution = Institution.new
  end

  def create
    @institution = Institution.new(params[:institution])
    if @institution.save
      redirect_to @institution
    else
      render 'new'
    end
  end

  def show
    @institution = Institution.find(params[:id])
  end

  def edit
    @institution = Institution.find(params[:id])
  end

  def update
    @institution = Institution.find(params[:id])
    @institution.update!(params[:institution])
    redirect_to @institution
  end

  def destroy
    Institution.find(params[:id]).destroy
    redirect_to institutions_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  def new
    @period = Period.new
  end

  def create
    @period = Period.create(params[:id])
  end

  def show
    @period = Period.find(params[:id])
  end

  def edit
    @period = Period.find(params[:id])
  end

  def update
    @period = Period.find(params[:id])
    @period.update!(params[:period])
    redirect_to @period
  end

  def destroy
    Period.find(params[:id]).destroy!
    redirect_to periods_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.haml
= simple_form_for @course, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :institution_id, collection: Institution.all
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), courses_path, :class => 'btn'

app/views/courses/edit.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courses/index.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @courses.each do |courses|
      %tr
        %td= link_to courses.name, course_path(courses)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(courses), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), course_path(courses), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_course_path, :class => 'btn btn-primary'

app/views/courses/new.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courses/show.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @course.name
%p
  %strong= model_class.human_attribute_name(:institution_id) + ':'
  %br
  = @course.institution_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), courses_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(@course), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), course_path(@course), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/institutions/_form.html.haml
= simple_form_for @institution, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), institutions_path, :class => 'btn'

app/views/institutions/edit.html.haml
- model_class = Institution
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/institutions/index.html.haml
- model_class = Institution
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @institutions.each do |institution|
      %tr
        %td= link_to institution.name, institution_path(institution)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_institution_path(institution), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), institution_path(institution), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_institution_path, :class => 'btn btn-primary'

app/views/institutions/new.html.haml
- model_class = Institution
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/institutions/show.html.haml
- model_class = Institution
.page-header
  %h1
    = @institution.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), institutions_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_institution_path(@institution), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), institution_path(@institution), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Centralestudantil</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/messages' %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.haml
%h1 Central Estudantil

app/views/periods/_form.html.haml
= simple_form_for @period, :html => { :class => 'form-horizontal' } do |f|
  = f.input :number
  = f.input :kind
  = f.input :course_id, collection: Course.all
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), periods_path, :class => 'btn'

app/views/periods/edit.html.haml
- model_class = Period
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/periods/index.html.haml
- model_class = Period
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:number)
      %th= model_class.human_attribute_name(:kind)
      %th= model_class.human_attribute_name(:course_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @periods.each do |period|
      %tr
        %td= link_to period.id, period_path(period)
        %td= period.number
        %td= period.kind
        %td= period.course_id
        %td=l period.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_period_path(period), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), period_path(period), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_period_path, :class => 'btn btn-primary'

app/views/periods/new.html.haml
- model_class = Period
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/periods/show.html.haml
- model_class = Period
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:number) + ':'
  %br
  = @period.number
%p
  %strong= model_class.human_attribute_name(:kind) + ':'
  %br
  = @period.kind
%p
  %strong= model_class.human_attribute_name(:course_id) + ':'
  %br
  = @period.course_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), periods_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_period_path(@period), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), period_path(@period), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'